### ISSUE TITLE
Wrong key name in interface

### ISSUE THREAD

**Issue by Kayxue** [Apacheli/urbanary#1]
Correct key name is permalink, not parmalink
![image](https://user-images.githubusercontent.com/26020165/158569296-00139a82-5011-427c-8acf-712156a20c53.png)
![image](https://user-images.githubusercontent.com/26020165/158569188-cf376b85-bf62-4b37-b075-c0121209759e.png)

**Comment by apacheli** [comment]
Released version 1.0.2 which fixes this 👍
